export const itemInfo = {
    'Apple': {
        itemId: '0006',
        description: 'A crunchy fruit that is both sweet and a bit tart.',
        itemName: 'Apple',
        itemConsumable: true,
        consumeEffects: {
            energy: 5,
            energyBonus: 1,
            eventChance: 1,
            attackBonus: 1,
            knockbackBonus: 1,
            exploreBonus: 1,
            defenceBonus: 1,
        },
    },
    'Raspberry': {
        itemId: '0002',
        description: 'A small fruit that is surprisingly energizing.',
        itemName: 'Raspberry',
        itemConsumable: true,
        consumeEffects: {
            energy: 5,
                eventChance: 1,
        },
    },
    'Lemon': {
        itemId: '0005',
        description: 'A tangy fruit that wakes up your senses.',
        itemName: 'Lemon',
        itemConsumable: true,
        consumeEffects: {
            energy: 5,
                eventChance: 1,
        },
    },
    'Strawberry': {
        itemId: '0003',
        description: 'A sweet fruit, perfect for a quick energy boost.',
        itemName: 'Strawberry',
        itemConsumable: true,
        consumeEffects: {
            energy: 6,
                eventChance: 1,
        },
    },
    'Peach': {
        itemId: '0001',
        description: 'A juicy fruit that provides some energy.',
        itemName: 'Peach',
        consumeEffects: {
            energy: 7,
                eventChance: 1,
        },
        itemConsumable: true,
    },
    'Blueberry': {
        itemId: '0014',
        description: 'A small fruit bursting with flavor. Good for a quick energy boost.',
        itemName: 'Blueberry',
        consumeEffects: {
            energy: 8,
                eventChance: 1,
        },
        itemConsumable: true,
    },
    'Egg': {
        itemId: '0007',
        description: 'A basic ingredient for many recipes. Can be consumed raw for minor energy.',
        itemName: 'Egg',
        itemConsumable: true,
        consumeEffects: {
            energy: 2,
                eventChance: 1,
        },
    },
    'Milk': {
        itemId: '0008',
        description: 'A basic ingredient for many recipes. Not consumable in its current form.',
        itemName: 'Milk',
        consumeEffects: {
            energy: 5,
                eventChance: 1,
        },
        itemConsumable: true,
    },
    'Flour': {
        itemId: '0009',
        description: 'A basic ingredient for many recipes. Not consumable in its current form.',
        itemName: 'Flour',
        itemConsumable: false,
    },
    'Cotton': {
        itemId: '0004',
        description: 'Soft and fluffy material. Not edible but useful in crafting.',
        itemName: 'Cotton',
        itemConsumable: false,
    },
    'Pebble': {
        itemId: '0010',
        description: 'A common stone. Not much use by itself but can be used in crafting.',
        itemName: 'Pebble',
        itemConsumable: false,
    },
    'Silk': {
        itemId: '0013',
        description: 'A fine, strong thread produced by silkworms. Not consumable but can be used in crafting.',
        itemName: 'Silk',
        itemConsumable: false,
    },
    'Gold': {
        itemId: '0015',
        description: 'A precious metal. Not consumable but highly valued in many cultures.',
        itemName: 'Gold',
        itemConsumable: false,
    },
    'Ruby': {
        itemId: '0016',
        description: 'A precious red gem. Not consumable but can be used in crafting.',
        itemName: 'Ruby',
        itemConsumable: false,
    },
    'Emerald': {
        itemId: '0012',
        description: 'A precious gem of dazzling green. Not consumable but can be used in crafting.',
        itemName: 'Emerald',
        itemConsumable: false,
    },
    'Diamond': {
        itemId: '0011',
        description: 'A rare and valuable gem. Not consumable but highly sought after.',
        itemName: 'Diamond',
        itemConsumable: false,
    },
    'Thread': {
        itemId: '0021',
        description: 'A luxurious thread. Maybe I can use it to makr something nice.',
        itemName: 'Thread',
        itemConsumable: false,
    },
    'Lemonpie': {
        itemId: '0018',
        description: 'A tangy pie that provides a significant energy boost.',
        itemName: 'Lemonpie',
        energyMultiplier: 1.05,
        itemConsumable: true,
        energy: 20,
        eventChance: 1,
        creationLevel: 1,
        creationExp: 50,
        ingredients: ['Lemon'],
    },
    'Strawberry Cake': {
        itemId: '0017',
        description: 'A delicious cake that provides a large energy boost.',
        itemName: 'Strawberry Cake',
        energy: 25,
        itemConsumable: true,
        energyMultiplier: 1.10,
        eventChance: 1,
        creationLevel: 3,
        creationExp: 100,
        ingredients: ['Strawberry', 'Milk', 'Egg', 'Flour'],
    },
    'attacking Collar': {
        itemId: '0020',
        description: 'Fashion is my passion.',
        itemName: 'attacking Collar',
        itemConsumable: false,
        attackMultiplier: 0.005,
        creationLevel: 4,
        creationExp: 100,
        ingredients: ['Gold', 'Ruby'],
    },
    'Royal Collar': {
        itemId: '0019',
        description: 'A cute lil collar',
        itemName: 'Royal Collar',
        itemConsumable: false,
        eventMultiplier: .01,
        creationLevel: 10,
        creationExp: 200,
        ingredients: ['Diamond', 'Emerald', 'Gold', 'Ruby'],
    },
    'Cape': {
        itemId: '0022',
        description: 'A very nice cape.',
        itemName: 'Cape',
        itemConsumable: false,
        luckMultiplier: 0.015,
        creationLevel: 15,
        creationExp: 1000,
        ingredients: ['Thread', 'Gold'],
    },
    // Add more items as needed
};