export const itemInfo = {
    'Apple': {
        itemId: '0006',
        description: 'A crunchy fruit that is both sweet and a bit tart.',
        itemName: 'Apple',
        rarity: 'common',
        itemConsumable: true,
        isEquippable: false,
        consumeEffects: {
            energy: 3,
        },
    },
    'Log': {
        itemId: '0010',
        description: 'A sturdy piece of wood. Not consumable but useful in crafting.',
        itemName: 'Log',
        itemConsumable: false,
        rarity: 'common',
        isEquippable: false,
    },
    'Raspberry': {
        itemId: '0002',
        description: 'A small fruit that is surprisingly energizing.',
        itemName: 'Raspberry',
        rarity: 'common',
        itemConsumable: true,
        isEquippable: false,
        consumeEffects: {
            energy: 3,
                eventChance: 1,
        },
    },
    'Lemon': {
        itemId: '0005',
        description: 'A tangy fruit that wakes up your senses.',
        itemName: 'Lemon',
        rarity: 'common',
        itemConsumable: true,
        isEquippable: false,
        consumeEffects: {
            energy: 2,
                eventChance: 1,
        },
    },
'Bone': {
        itemId: '0039',
        description: 'A bone from a small animal. Not consumable but can be used in crafting.',
        itemName: 'Bone',
        rarity: 'rare',
        isEquippable: false,
        friendlyName: 'Bone',
        itemConsumable: false,
    },

   'Strawberry': {
        itemId: '0003',
        description: 'A sweet fruit, perfect for a quick energy boost.',
        itemName: 'Strawberry',
        rarity: 'common',
        isEquippable: false,
        itemConsumable: true,
        consumeEffects: {
            energy: 2,
        },
    },
    'Peach': {
        itemId: '0001',
        description: 'A juicy fruit that provides some energy.',
        itemName: 'Peach',
        rarity: 'common',
        isEquippable: false,
        consumeEffects: {
            energy: 4,
            eventChance: 1,
        },
        itemConsumable: true,
    },
    'Blueberry': {
        itemId: '0014',
        description: 'A small fruit bursting with flavor. Good for a quick energy boost.',
        itemName: 'Blueberry',
        rarity: 'uncommon',
        isEquippable: false,
        consumeEffects: {
            energy: 3,
        },
        itemConsumable: true,
    },
    'Egg': {
        itemId: '0007',
        description: 'A basic ingredient for many recipes. Can be consumed raw for minor energy.',
        itemName: 'Egg',
        isEquippable: false,
        rarity: 'common',
        itemConsumable: true,
        consumeEffects: {
            energy: 1,
                eventChance: 1,
        },
    },
    'Milk': {
        itemId: '0008',
        description: 'A basic ingredient for many recipes. Not consumable in its current form.',
        itemName: 'Milk',
        isEquippable: false,
        rarity: 'common',
        consumeEffects: {
            energy: 3,
                eventChance: 1,
        },
        itemConsumable: true,
    },
    'Flour': {
        itemId: '0009',
        description: 'A basic ingredient for many recipes. Not consumable in its current form.',
        itemName: 'Flour',
        isEquippable: false,
        rarity: 'common',
        itemConsumable: false,
    },
    'Cotton': {
        itemId: '0004',
        description: 'Soft and fluffy material. Not edible but useful in crafting.',
        itemName: 'Cotton',
        rarity: 'common',
        itemConsumable: false,    
            isEquippable: false,
    },
    'Pebble': {
        itemId: '0010',
        description: 'A common stone. Not much use by itself but can be used in crafting.',
        itemName: 'Pebble',
        rarity: 'common',
        isEquippable: false,

        itemConsumable: false,
    },
    'Silk': {
        itemId: '0013',
        description: 'A fine, strong thread produced by silkworms. Not consumable but can be used in crafting.',
        itemName: 'Silk',
        rarity: 'uncommon',
        isEquippable: false,

        itemConsumable: false,
    },
    'Gold': {
        itemId: '0015',
        description: 'A precious metal. Not consumable but highly valued in many cultures.',
        itemName: 'Gold',
        rarity: 'rare',
        itemConsumable: false,        
        isEquippable: false,


    },
    'Ruby': {
        itemId: '0016',
        description: 'A precious red gem. Not consumable but can be used in crafting.',
        itemName: 'Ruby',
        rarity: 'rare',
        itemConsumable: false,        
        isEquippable: false,

    },
    'Emerald': {
        itemId: '0012',
        description: 'A precious gem of dazzling green. Not consumable but can be used in crafting.',
        itemName: 'Emerald',
        rarity: 'rare',
        itemConsumable: false,
        isEquippable: false,

    },
    'Diamond': {
        itemId: '0011',
        description: 'A rare and valuable gem. Not consumable but highly sought after.',
        itemName: 'Diamond',
        rarity: 'ultrarare',
        itemConsumable: false,
        isEquippable: false,

    },
    'Thread': {
        itemId: '0021',
        description: 'A luxurious thread. Maybe I can use it to makr something nice.',
        itemName: 'Thread',
        rarity: 'ultrarare',
        itemConsumable: false,
        isEquippable: false,
    },
    'Lemonpie': {
        itemId: '0018',
        description: 'A tangy pie that provides a significant energy boost.',
        itemName: 'Lemonpie',
        itemConsumable: true,
        rarity: 'common',
        friendlyName: 'Lemon Pie',
        isEquippable: false,
        consumeEffects: {
            energy: 20,
        },
        ingredients: ['Lemon', 'Milk', 'Egg', 'Flour'],
    },
    'Strawberry Cake': {
        itemId: '0017',
        description: 'A delicious cake that provides a large energy boost.',
        itemName: 'Strawberry Cake',
        friendlyName: 'Strawberry Cake',
        rarity: 'common',
        itemConsumable: true,
        isEquippable: false,
        consumeEffects: {
            energy: 20,
        },
        ingredients: ['Strawberry', 'Milk', 'Egg', 'Flour'],
    },
    'Red Collar': {
        itemId: '0020',
        description: 'Cute and basic.',
        itemName: 'Red Collar',
        rarity: 'common',
        friendlyName: 'Collar',
        isEquippable: true,
        itemConsumable: false,
        equipmentSlot: 'collar',
        equipmentName: 'collar',
        light: true,
        lightIntensity: .1,
        fireBonus: 1,
        repelChance: 0.05,
        lightRadius: 80,
        attackMultiplier: 0.005,
        creationLevel: 4,
        creationExp: 100,
        ingredients: ['Silk', 'Cotton', 'Cotton'],
    },
    'Red Collar Bell Brass': {
        itemId: '0025',
        description: 'Fashion is my passion.',
        itemName: 'Red Collar Bell Brass',
        rarity: 'common',
        friendlyName: 'Brass Bell Collar',
        itemConsumable: false,
        isEquippable: true,
        equipmentSlot: 'collar',
        equipmentName: 'redcollarbellbrass',
        light: true,
        lightIntensity: 0.1,
        repelChance: 0.1,
        fireBonus: 2,
        lightRadius: 120,
        attackMultiplier: 0.005,
        creationLevel: 6,
        creationExp: 200,
        ingredients: ['Red Collar', 'Thread', 'Emerald'],
    },
    'Red Collar Bell Silver': {
        itemId: '0022',
        description: 'Silver is so shiny.',
        itemName: 'Red Collar Bell Silver',
        rarity: 'common',
        friendlyName: 'Silver Bell Collar',
        itemConsumable: false,
        isEquippable: true,
        equipmentSlot: 'collar',
        equipmentName: 'redcollarbellsilver',
        light: true,
        lightIntensity: 0.1,
        repelChance: 0.1,
        fireBonus: 3,
        lightRadius: 150,
        attackMultiplier: 0.005,
        creationLevel: 6,
        creationExp: 200,
        ingredients: ['Red Collar Bell Brass','Ruby', 'Thread', 'Thread'],
    },
    'Red Collar Bell Gold': {
        itemId: '0021',
        description: 'It looks very expensive and makes a pleasant sound.',
        itemName: 'Red Collar Bell Gold',
        itemConsumable: false,
        isEquippable: true,
        equipmentSlot: 'collar',
        rarity: 'common',
        equipmentName: 'redcollarbellgold',
        friendlyName: 'Gold Bell Collar',
        light: true,
        fireBonus: 4,
        lightIntensity: 0.1,
        repelChance: 0.12,
        lightRadius: 200,
        attackMultiplier: 0.005,
        creationLevel: 20,
        creationExp: 500,
        ingredients: ['Red Collar Bell Silver','Gold', 'Thread', 'Thread', 'Thread'],
    },

};